# Generated by Django 2.1.7 on 2020-03-22 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Main',
            new_name='Blog',
        ),
    ]
